version: 1
disable_existing_loggers: False

loggers:
    ocata:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
    newton_base:
      handlers': [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
    common:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
handlers:
    console_handler:
        level: "DEBUG"
        class: "logging.StreamHandler"
        formatter: "mdcFormat"
    file_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/openstack/ocata/ocata.log"
        formatter: "mdcFormat"
        maxBytes: 1024*1024*50
        backupCount: 10
formatters:
    standard:
        format: "%(asctime)s|||||%(name)s||%(thread)||%(funcName)s||%(levelname)s||%(message)s"
    mdcFormat:
        format: "%(asctime)s|||||%(name)s||%(thread)s||%(funcName)s||%(levelname)s||%(message)s||||%(mdc)s \t"
        mdcfmt: "{requestID} {invocationID} {serviceName} {serviceIP}"
        datefmt: "%Y-%m-%d %H:%M:%S"
        (): onaplogging.mdcformatter.MDCFormatter

